title: Teachair
description: Teachair - открытая, гибкая, современная платформа с глубокой интеграцией в экосистему Telegram и встроенными функциями Искусственного интеллекта (AI)
url: https://teachair.app
baseurl: /
logo: /assets/images/logo/logo-2.svg